modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="dreamscape"
version="0.0.1.1"
displayName="DreamScape"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="crtca, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dreamscape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration